# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: csharp
dist: trusty
dotnet: 1.0.1
mono: latest

os:
 - osx
 - linux

before_install:
 - date -u
 - uname -a
 - env | sort

solution: LibGit2Sharp.sln

# Build libgit2, LibGit2Sharp and run the tests
script:
 - ./build.libgit2sharp.sh 'LEAKS_IDENTIFYING'

# Only watch the development branch
branches:
 only:
   - master
   - /^maint.*/
   - portable
   - dotnetcore

# Notify of build changes
notifications:
 email:
  - emeric.fermas@gmail.com
