# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: csharp
mono:
 - 3.12.0
 - 4.2.3

os:
 - osx
 - linux

# The newer image cannot find mono 3.12 in the PATH
osx_image: xcode6.4

env:
 global:
  - MONO_OPTIONS=--debug

before_install:
 - date -u
 - uname -a
 - env | sort

solution: LibGit2Sharp.sln

# Build libgit2, LibGit2Sharp and run the tests
script:
 - ./build.libgit2sharp.sh 'LEAKS_IDENTIFYING'

# Only watch the development branch
branches:
 only:
   - vNext
   - master

# Notify of build changes
notifications:
 email:
  - emeric.fermas@gmail.com
